openapi: 3.1.0
info:
  contact:
    email: https://github.com/saviynt
    name: Saviynt Developers Team
  description: Saviynt Tasks API
  title: Saviynt Tasks API
  version: "1.0"
servers:
- url: http://localhost:3000
tags:
- name: Tasks
paths:
  /ECM/api/v5/checkTaskStatus:
    post:
      description: This API can be used to check the task status. Response can return
        task status as “New/Complete/In Progress/Discontinued”.
      operationId: checkTaskStatus
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CheckTaskStatusRequest'
        description: ""
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckTaskStatusResponse'
          description: OK
      summary: Check Task Status
      tags:
      - Tasks
  /ECM/api/v5/updateTasks:
    post:
      description: It can update certain params of a task as well as complete a task.
      operationId: updateTasks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTasksRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTasksResponse'
          description: OK
      summary: Update Tasks
      tags:
      - Tasks
components:
  schemas:
    CheckTaskStatusRequest:
      properties:
        taskid:
          type: string
          x-stoplight:
            id: 9au7lq8dxsbp3
      required:
      - taskid
      title: CheckTaskStatusRequest
      x-stoplight:
        id: u7nkg6jz4b8dl
    CheckTaskStatusResponse:
      description: ""
      example:
        Status: Status
        UpdateDate: UpdateDate
        ProvisioningMetadata: "{}"
        Comments: Comments
        ProvisioningComments: ProvisioningComments
        UpdateUser: UpdateUser
      properties:
        Status:
          description: |-
            Can be null or one of the following:

            1. `New`
            2. `In Progress`
            3. `Complete`
            4. `Discontinued`
            5. `Pending Create`
            6. `Pending Provision`
            7. `Provisioning Failed`
            8. `Error`
            9. `No Action Required`
          type: string
          x-stoplight:
            id: xvc1tuukf1ia3
        UpdateDate:
          type: string
          x-stoplight:
            id: eqvgny125a1jr
        Comments:
          type: string
          x-stoplight:
            id: uht8mb3oqa84f
        ProvisioningComments:
          type: string
          x-stoplight:
            id: 0zwyd4r8v825f
        UpdateUser:
          type: string
          x-stoplight:
            id: 4dbj2dneg5jvm
        ProvisioningMetadata:
          type: object
          x-stoplight:
            id: pp42szdd91wr3
      title: CheckTaskStatusResponse
      x-stoplight:
        id: ev00l66p331k3
    UpdateTaskRequestInfo:
      description: |-
        1. `updatetype` (if this is set to "completetask" then refer completetask api and pass appropriate params as well),
        1. `comments`
        1. `provisioningComments`
        1. `provisioningMetadata`
        1. `password`
        1. `status`
        1. `ticketId`
        1. `taskownerusergroup`
        1. `taskowneruser`
        1. `updateuser` - username of user who is updating the task,
        1. `completeassociatedtasks` - true / false,
        1. `emailto`
        1. `notify` - to pick up data from the task, supported values - "notify":["USER","requestor","MANAGER"],
        1. `from`
        1. `subject`
        1. `emailbody`
      example:
        taskid: taskid
        status: "1"
      properties:
        taskid:
          type: string
          x-stoplight:
            id: zuqc9n0uloizr
        status:
          description: |-
            Use the following numeric status codes to represent the following status. These string status values are returned in the `checkTaskStatus` endpoint.
            1: New
            2: In Progress
            3: Complete
            4: Discontinued
            5: Pending Create
            6: Pending Provision
            7: Provisioning Failed
            8: Error
            9: No Action Required
          enum:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
          - "9"
          type: string
          x-stoplight:
            id: f1yxjoi1tnz2y
      required:
      - status
      - taskid
      title: UpdateTaskRequestInfo
      x-stoplight:
        id: sclcppzc5yn6n
    UpdateTaskResponseInfo:
      properties:
        msg:
          type: string
          x-stoplight:
            id: pqkj5h32eikew
        errorCode:
          type: string
          x-stoplight:
            id: tpd9zvjvqu450
      required:
      - errorCode
      - msg
      title: UpateTaskResponseInfo
      x-stoplight:
        id: 5txk1wm5gp1ok
    UpdateTasksResponse:
      additionalProperties:
        $ref: '#/components/schemas/UpdateTaskResponseInfo'
      title: UpdateTasksResponse
      x-stoplight:
        id: 252egi48pfxga
    UpdateTasksRequest:
      description: ""
      example:
        taskKeyToUpdate:
        - taskid: taskid
          status: "1"
        - taskid: taskid
          status: "1"
        updateuser: updateuser
      properties:
        taskKeyToUpdate:
          items:
            $ref: '#/components/schemas/UpdateTaskRequestInfo'
          type: array
          x-stoplight:
            id: ew8s4sdh02wzl
        updateuser:
          type: string
          x-stoplight:
            id: j99s86kf7ltqs
      required:
      - taskKeyToUpdate
      title: UpdateTasksRequest
      x-stoplight:
        id: 3rtx1z2yu3dbq
x-stoplight:
  id: vqaggj7sqeqfe
