openapi: 3.0.0
info:
  description: API endpoints extracted from the 'Endpoints' section of Identity Administration.
  title: Endpoints API
  version: 1.0.0
servers:
- url: /
security:
- BearerAuth: []
paths:
  /createEndpoint:
    post:
      description: "This API creates an endpoint in EIC.\n\nThe `Authorization` must\
        \ have a `Bearer` followed by a `Token`.\n\nMandatory parameters:\n\n- `endpointname`:\
        \ Enter the name of the endpoint. Provide a logical name for the endpoint\
        \ that will help you to easily identify the endpoint.\n- `displayName`: Enter\
        \ a name for the endpoint that will be displayed in the user interface. Display\
        \ Name can be different from Endpoint Name.\n- `securitysystem:`Select the\
        \ security system for which you want to create an endpoint. The security system\
        \ encapsulates the endpoint along with other endpoints sharing the same connections,\
        \ workflows, or more.\n    \n\nOptional parameters:\n\n`description`,  \n\
        `ownerType`,  \n`owner`,  \n`resourceOwnerType`,  \n`resourceOwner`,  \n`customproperty`\
        \ - N is between 1 to 30,  \n`custompropertyLabel` - N is between 1 to 30,\
        \  \n`accountNameRule`,  \n`accessquery`,  \n`enableCopyAccess`,  \n`disableNewAccountRequestIfAccountExists`,\
        \  \n`disableRemoveAccount`,  \n`disableModifyAccount`,  \n`blockInflightRequest`,\
        \  \n`userAccountCorrelationRule`,  \n`connectionconfig`"
      parameters: []
      responses:
        "200":
          description: Successful response
      summary: Create Endpoint
  /updateEndpoint:
    put:
      description: "This API updates an endpoint within the Saviynt EIC.\n\nThe `Authorization`\
        \ must have a `Bearer` followed by a `Token`.\n\nNote: From Release v23.9,\
        \ a new parameter **`requestableRoleType`** is introduced to update the requestable\
        \ options of a Role for a particular endpoint.\n\nMandatory parameters:\n\n\
        `endpointname`  \n`roleType` Supports valid case-senstive string values such\
        \ as \"Enabler”, “Transactional”, “EmergencyAccess”, “Enterprise”, and “Application”\
        \n\nOptional parameters:\n\n`securitysystem`,  \n`displayName`,  \n`description`,\
        \  \n`ownerType`,  \n`owner`,  \n`resourceOwnerType`,  \n`resourceOwner`,\
        \  \n`customproperty` - N is between 1 to 30,  \n`custompropertyLabel` - N\
        \ is between 1 to 30,  \n`accountNameRule`,  \n`accessquery`,  \n`enableCopyAccess`,\
        \  \n`disableNewAccountRequestIfAccountExists`,  \n`disableRemoveAccount`,\
        \  \n`disableModifyAccount`,  \n`blockInflightRequest`,  \n`userAccountCorrelationRule`,\
        \  \n`createEntTaskforRemoveAcc`,  \n`connectionconfig requestableRoleType\
        \ requestOption` - Supports valid case-senstive string values such as “None”\
        , “DropDownSingle”, “Table”, and “TableOnlyAdd”  \n`required` - Supports valid\
        \ boolean values are true and false`requestedQuery/selectedQuery` Supports\
        \ string values in double quotes  \n`showOn` - Supports valid case-sensitive\
        \ string values such as \"All\", \"ShowOnApplicationRequest\", and \"ShowOnServiceAccountRequest\"\
        . specify the value to display the roles on Application Requests, Service\
        \ Account Requests, or both. This parameter is available from the Release\
        \ v24.6 onwards."
      parameters: []
      responses:
        "200":
          description: Successful response
      summary: Update Endpoint
  /getEndpoints:
    post:
      description: "This API returns list of Endpoints in EIC.\n\nThe `Authorization`\
        \ must have `Bearer` followed by `Token`.\n\nOptional params:  \n`connectionType`,\
        \  \n`endpointkey`,  \n`endpointname`,  \n`max`,  \n`offset`,  \n`filterCriteria`\n\
        \n**Note**: You must specify the value for `endpointkey` parameter in array.\
        \ Fr example, `\"endpointkey\" : [5]`."
      parameters: []
      responses:
        "200":
          description: Successful response
      summary: Get List of Endpoints
  /createEntitlementType:
    post:
      description: |-
        This API creates Entitlement Type in SSM.

        The `Authorization` must have `Bearer` followed by `Token`.

        Mandatory params:

        `entitlementname`,
        `endpointname`

        Optional params:

        `entitlementdescription`,
        `customproperty<N>` - customproperty 1 to 5,
        `workflow`
      parameters: []
      responses:
        "200":
          description: Successful response
      summary: Create Entitlement Type
  /updateEntitlementType:
    put:
      description: "This API updates Entitlement Type in SSM.\r\n\r\nThe `Authorization`\
        \ must have `Bearer` followed by `Token`.\r\n\r\nMandatory params:\r\n\t`entitlementname`,\r\
        \n\t`endpointname`,\r\n\t\r\nOptional params:\r\n\t`entitlementdescription`,\r\
        \n\t`workflow`,\r\n\t`customproperty<N>`,\r\n\t`availableQueryServiceAccount`,\r\
        \n\t`selectedQueryServiceAccount`, \r\n\t`arsRequestableEntitlementQuery`,\
        \ \r\n\t`arsSelectedEntitlementQuery` , \r\n\t`createTaskAction` - it can\
        \ be one value or list of values. The values can be [\"noAction\",\"removeTaskForExistingEntitlements\"\
        , \"enableRollback\"],\r\n\t`requestDatesConfJson` , \r\n\t`startDateInRevokeRequest`\
        \ , \r\n\t`startEndDateInRequest` ,\r\n\t`allowRemoveAllEntitlementInRequest`\
        \ , \r\n\t`orderindex` , \r\n\t`requiredinrequest` ,\r\n\t`hiearchyrequired`\
        \ , \r\n\t`requestoption`\r\n\t\r\n\t\r\n`requestoption` param values can\
        \ be - \r\nSHOW_BUT_NOTREUESTABLESINGLE/ \r\nSHOW_BUT_NOTREUESTABLEMULTIPLE/\
        \ \r\nNONE/ \r\nSINGLE/ \r\nMULTIPLE/ \r\nTABLE/ \r\nFREEFORMTEXT/ \r\nTABLENOREMOVE/\
        \ \r\nRADIOBUTN/ \r\nCHECKBOXN/ \r\nREADONLYTABLE/ \r\nNONE_BUT_CREATETASK"
      parameters: []
      responses:
        "200":
          description: Successful response
      summary: Update Entitlement Type
  /getEntitlementTypes?entitlementname=testEnt81:
    get:
      description: |-
        This API returns list of Entitlement Types in SSM.

        The `Authorization` must have `Bearer` followed by `Token`.

        Optional params:

        `entitlementname`,
        `max`,
        `offset`,
        `endpointname`
      parameters: []
      responses:
        "200":
          description: Successful response
      summary: Get List of Entitlement Types
  /createDynamicAttribute:
    post:
      description: |-
        This API creates dynamic attributes in EIC.

        The `Authorization` must have `Bearer` followed by `Token`.

        Mandatory params:

        `securitysystem`

        `endpoint`

        `updateuser`

        `dynamicattributes` - `attributename`, `requesttype`(ACCOUNT/PROPOSED ENTITLEMENT OWNER/ENTITLEMENT OWNER ATTESTATION/ROLE/SERVICE ACCOUNT)

        Optional params:

        `dynamicattributes` - other dynamic attribute parameters:

        - `attributetype`: Specify the attribute type based on which you want to filter and display the dynamic attributes.The various types of attribute types are: Single select from Sql Query, ENUM, Password, Boolean (True,False), String, Check Box, Date, and so on.
        - `attributename`: Specify the dynamic attribute name to be used for filtering out and calling the respective attribute to be displayed.
        - `Attribute Group`: Attribute Group provides you an option to group or categorize and display the dynamic attributes in the Access Requests request form.
        - `Order Index`: Specify the sequence where you want to display the dynamic attributes. You can specify values such as 0,1, 2, 3 and so on. Order index with lower values is displayed first and those with higher values are displayed later.
        - `attributelable`: Specify the name of the attribute, which you want to display in the Access Requests request form. You can apply the following font styling to the label:
            - `##SavBoldStart##Attribute_Name##SavBoldEnd##`
            - `##SavUnderlineStart##Attribute_Name##SavItalicEnd##`
            - `##SavUnderlineStart##Attribute_Name##UnderlineEnd##`
            - `##SavAnchorStart####SavUrlStart##https://exampleorg.com##SavUrlEnd####SavUrlTextStart##URL_Text##SavUrlTextEnd####SavAnchorEnd##`
      parameters: []
      responses:
        "200":
          description: Successful response
      summary: Create Dynamic Attribute
  /updateDynamicAttribute:
    put:
      description: |-
        This API updates dynamic attributes in SSM.

        The `Authorization` must have `Bearer` followed by `Token`.

        Mandatory params:

        `securitysystem`

        `endpoint`

        `updateuser`

        `dynamicattributes` - `attributename`

        Optional params:

        - `dynamicattributes` - other attributes of dynamic attributes
        - `attributetype`(BOOLEAN/NUMBER/STRING/ENUM/MULTIPLE SELECT FROM LIST/MULTIPLE SELECT FROM SQL QUERY/SINGLE SELECT FROM SQL QUERY/PASSWORD/LARGE TEXT/CHECK BOX/DATE)
        - `requesttype`(ACCOUNT/PROPOSED ENTITLEMENT OWNER/ENTITLEMENT OWNER ATTESTATION/ROLE/SERVICE ACCOUNT)
        - `attributelable`: Specify the name of the attribute, which you want to display in the Access Requests request form. You can apply following font styling to the label:
            - **##SavBoldStart##**_**Attribute_Name**_**##SavBoldEnd##**
            - **##SavItalicStart##**_**Attribute_Name**_**##SavItalicEnd##**
            - **##SavUnderlineStart##**_**Attribute_Name**_**##SavItalicEnd##**
            - **##SavUrlStart##**_**Attribute_Name**_**##SavUrlEnd##**
            - **##SavAnchorStart####SavUrlStart##**[<b>https://exampleorg.com##SavUrlEnd####SavUrlTextStart##</b>]()_**URL_Text**_**##SavUrlTextEnd####SavAnchorEnd##**
      parameters: []
      responses:
        "200":
          description: Successful response
      summary: Update Dynamic Attribute
  /fetchDynamicAttribute:
    get:
      description: |-
        This API fetches the dynamic attributes in SSM.

        The `Authorization` must have `Bearer` followed by `Token`.

        Optional params:

        `securitysystem`

        `endpoint`

        `dynamicattributes`

        `max`, `offset`,

        `requesttype` - can be ['ACCOUNT', 'PROPOSED ENTITLEMENT OWNER', 'ENTITLEMENT OWNER ATTESTATION', 'ROLE', 'SERVICE ACCOUNT','USER'],

        `loggedinuser`
      parameters: []
      responses:
        "200":
          description: Successful response
      summary: Fetch Dynamic Attributes
  /deleteDynamicAttribute:
    delete:
      description: |-
        This API deletes dynamic attributes in SSM.

        The `Authorization` must have `Bearer` followed by `Token`.

        Mandatory params:

        `securitysystem`

        `endpoint`

        `updateuser`

        `dynamicattributes` - attributename list
      parameters: []
      responses:
        "200":
          description: Successful response
      summary: Delete Dynamic Attribute
components:
  schemas: {}
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
