openapi: 3.1.0
info:
  contact:
    email: https://github.com/saviynt
    name: Saviynt Developers Team
  description: Saviynt Job Control API Spec
  title: Saviynt Job Control API
  version: "1.0"
servers:
- url: http://localhost:3000
tags:
- name: Job Control
paths:
  /ECM/api/v5/createUpdateTrigger:
    post:
      description: |-
        This API call can be used to create and update a trigger for a particular `jobgroup` in Saviynt.

        Starting with Release v24.7, a new `analysistypes` parameter has been introduced for the **Recommendations** job. To execute an analysis type using this API, you can use the `analysistypes` parameter and specify the following values in its request:

        * 0 – Run All Steps
        * 1 – Run Attribute Discovery
        * 2 – Generate Correlation Rules
        * 3 – Rule Consolidation for Access
        * 4 – Rule Consolidation for Apps
        * 5 – Compute Access Confidence
        * 6 – Compute Model Performance Statistics
        * 7 – Incremental Rule Creation
      operationId: createUpdateTrigger
      responses:
        "200":
          description: OK
      summary: Create and Update Trigger
      tags:
      - Job Control
  /ECM/api/v5/checkJobStatus:
    post:
      description: This API is used to fetch the status of any job other than Data
        Import Job.
      operationId: checkJobStatus
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CheckJobStatusRequest'
        description: ""
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckJobStatusResponse'
          description: OK
      summary: Check Job Status
      tags:
      - Job Control
  /ECM/api/v5/deleteTrigger:
    post:
      description: This API call can be used to delete a trigger for a particular
        "jobgroup" in Saviynt.
      operationId: deleteTrigger
      responses:
        "200":
          description: OK
      summary: Delete Trigger
      tags:
      - Job Control
  /ECM/api/v5/runJobTrigger:
    post:
      description: |-
        This API call can be used to run a job trigger in Saviynt.

        The following cases illustrate different scenarios on the usage of the `analyticsAdvanceQuery` parameter in the API:

        * Case 1: When you configure the `analyticsAdvanceQuery` within the payload, set the `defaultActionForAnalytics` as `"true"`, and then execute the control from the API, it overrides the default action and the advanced query configuration within the job trigger.
        * Case 2: When you configure the `analyticsAdvanceQuery` within the payload, set the `defaultActionForAnalytics` as `"false"`, and then execute the control from the API without performing the default actions configured in the control, it overrides the default action and the advanced query configuration within the job trigger.
        * Case 3: When you do not configure both the `analyticsAdvanceQuery` and the `defaultActionForAnalytics`x, the default action will depend on the configuration provided in the analytics job trigger.

        The following cases illustrate different scenarios on the usage of the `analyticsCategories` parameter in the API:

        * Case 1: When you set the "defaultActionForAnalytics" as "true" to perform default actions for analytics controls by executing the control from job API, it will override the default action configuration within the job trigger.
        * Case 2: When you set the "defaultActionForAnalytics" as "false" to not perform default actions for analytics controls by executing the control from job API, it will override the default action configuration within the job trigger.
        * Case 3: When the defaultActionForAnalytics parameter is not set in the payload, the default action will depend on the configuration provided in the analytics job trigger.
      operationId: runJobTrigger
      responses:
        "200":
          description: OK
      summary: Run Job Trigger
      tags:
      - Job Control
  /ECM/api/v5/fetchJobMetadata:
    post:
      description: |-
        This API call return job metadata for the last run of a job in Saviynt.

        Note: The structure of the result param in response can change based upon the Job History saved in Saviynt
      operationId: fetchJobMetadata
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FetchJobMetadataRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchJobMetadataResponse'
          description: OK
      summary: Fetch Job Metadata
      tags:
      - Job Control
  /ECM/api/v5/createTriggers:
    post:
      description: This API is used to create job triggers.
      operationId: createTriggers
      responses:
        "200":
          description: OK
      summary: Create Triggers
      tags:
      - Job Control
  /ECM/api/v5/resumePauseJobs:
    post:
      description: |-
        Starting with Release v23.10, the `resumePauseJobs` API enables you to pause jobs based on their job type and job name.

        When a job is paused, its status is displayed as Paused on the Job Control Panel page.
      operationId: resumePauseJobs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResumePauseJobsRequest'
      responses:
        "200":
          content:
            text/plain:
              examples:
                Successful Pause:
                  value: Job(s) Paused successfully
                Successful Resume:
                  value: Job(s) Resumed successfully
                Error on No Triggers:
                  value: No triggers found
              schema:
                type: string
          description: OK
        "201":
          content:
            text/plain:
              schema:
                type: string
          description: Created
      summary: Resume Pause Jobs
      tags:
      - Job Control
components:
  schemas:
    CheckJobStatusRequest:
      properties:
        jobgroup:
          type: string
          x-stoplight:
            id: 8ypc6y1fo4t4n
        jobname:
          type: string
          x-stoplight:
            id: afvzbom2l6dmo
      required:
      - jobgroup
      - jobname
      title: CheckJobStatusRequest
      x-stoplight:
        id: sgskilxuqx1ng
    CheckJobStatusResponse:
      example:
        msg: msg
        errorCode: errorCode
      properties:
        msg:
          type: string
          x-stoplight:
            id: 8f07qxf5fpmnu
        errorCode:
          type: string
          x-stoplight:
            id: vywsiuk8okt0v
      title: CheckJobStatusResponse
      x-stoplight:
        id: 2gqodxah1rk0u
    DeleteTriggerRequest:
      properties:
        jobname:
          type: string
          x-stoplight:
            id: s5k92socxnck0
        triggername:
          type: string
          x-stoplight:
            id: f5egb9c3qcldo
        jobgroup:
          type: string
          x-stoplight:
            id: ze7cut4s3g2r0
      required:
      - jobname
      title: DeleteTriggerRequest
      x-stoplight:
        id: c2oolhf2vbnmh
    FetchJobMetadataRequest:
      description: ""
      example:
        triggername: triggername
        jobname: jobname
        jobgroup: jobgroup
      properties:
        jobname:
          type: string
          x-stoplight:
            id: debkp5wftr5l6
        triggername:
          type: string
          x-stoplight:
            id: qt5w1qws7s64s
        jobgroup:
          type: string
          x-stoplight:
            id: eg0od7k6qppj3
      required:
      - jobname
      title: FetchJobMetadataRequest
      x-stoplight:
        id: t7fzs0it0fdhv
    FetchJobMetadataResponse:
      example:
        msg: msg
        result:
          key: ""
        errorCode: 0
      properties:
        msg:
          type: string
          x-stoplight:
            id: s5h1a3wf6stjx
        errorCode:
          type: integer
          x-stoplight:
            id: 5cjzjtra4phal
        result:
          additionalProperties: true
          type: object
          x-stoplight:
            id: t99p2zgl9t1al
      title: FetchJobMetadataResponse
      x-stoplight:
        id: r6jctqk6z8npb
    DeleteTriggerResponse:
      properties:
        msg:
          type: string
          x-stoplight:
            id: 1kzo52rrekugx
        errorCode:
          type: string
          x-stoplight:
            id: f755k6c3mpnec
      title: DeleteTriggerResponse
      x-stoplight:
        id: 5hebwug4olh4h
    ResumePauseJobsRequest:
      example:
        triggername: triggername
        action: PAUSE
        jobname: jobname
      properties:
        action:
          enum:
          - PAUSE
          - RESUME
          type: string
          x-stoplight:
            id: 527d2rxyp6gw3
        triggername:
          type: string
          x-stoplight:
            id: cmbimxzyk4and
        jobname:
          type: string
          x-stoplight:
            id: 979nwfj8yobyy
      required:
      - action
      title: ResumePauseJobsRequest
      x-stoplight:
        id: ru7xvuen9hqhr
    ResumePauseJobsResponse:
      properties:
        id:
          type: string
      title: ResumePauseJobsResponse
      x-stoplight:
        id: jq15kv6uajh6e
x-stoplight:
  id: wh6tzb3gstrbw
